---
- name: Configure an Apache server
  hosts: all
  become: yes
  roles:
    - role: manala.motd
      manala_motd_message: "Welcome to this Satellite-Ansible managed {{ foreman.operatingsystem_name }} Postgres host"
    - role: olibob.apache
    - role: FlatKey.firewalld
      firewalld_service_rules:
        http:
          state: enabled
          zone: public
          permanent: true
          immediate: true

