---
- name: Configure a base RHEL server
  hosts: all
  become: yes
  roles:
    - role: manala.motd
      manala_motd_message: "Welcome to this Satellite-Ansible managed {{ foreman.operatingsystem_name }} base host"
    - role: FlatKey.firewalld
      default_zone: public
