---
- name: Install RHCS dependencies
  hosts: all
  become: yes
  tasks:
    - name: Split cluster_peers
      set_fact: peers={{ foreman_params.cluster_peers.split(" ")|sort }}
    - name: Determine master
      set_fact: master=peers[0]
    - name: Install RPMs
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - pcs
        - pacemaker
        - fence-agents-all
    - name: Open firewall ports
      firewalld:
        service: high-availability
        immediate: yes
        permanent: true
        state: enabled
    - name: Set hacluster passwd
      shell: echo {{ foreman_params.hacluster_passwd }} | passwd --stdin hacluster
    - name: Start pcsd
      service:
        name: pcsd
        enabled: yes
        state: started
    - name: Authenticate pcs
      shell: pcs cluster auth {{ peers|join(" ") }} -u hacluster -p {{ foreman_params.hacluster_passwd }}

    - debug:
        msg: Master is {{ master }}
    # name: Wait for all cluster members to be up


    # name: Create cluster

