---
- name: Install RHCS dependencies
  hosts: all
  become: yes
  tasks:

    - name: Split cluster_peers
      set_fact: peer_list={{ foreman_params.hacluster_peers.split(" ")|sort }}
    - name: Determine master
      set_fact: master={{ peer_list[0] }}

    - name: Install RPMs
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - pcs
        - pacemaker
        - fence-agents-all

    - name: Open firewall ports
      firewalld:
        service: high-availability
        immediate: yes
        permanent: true
        state: enabled

    - name: Set hacluster passwd
      shell: echo {{ foreman_params.hacluster_passwd }} | passwd --stdin hacluster

    - name: Start pcsd
      service:
        name: pcsd
        enabled: yes
        state: started

    - name: Wait until all nodes in cluster are up
      wait_for:
        port: 22
        host: "{{ item }}"
      with_items: "{{ peer_list }}"

    - name: Check if cluster already running
      command: pcs cluster status
      register: cluster_status
      ignore_errors: true

    - name: Authenticate pcs
      command: pcs cluster auth {{ foreman_params.hacluster_peers }} -u hacluster -p {{ foreman_params.hacluster_passwd }}
      when: cluster_status is failed

    - name: Create cluster
      command: pcs cluster setup --start --name {{ foreman_params.hacluster_name }} {{ foreman_params.hacluster_peers }}
      delegate_to: "{{ master }}"
      run_once: true
      when: cluster_status is failed






    # name: Wait for all cluster members to be up


    # name: Create cluster

