---
- name: Configure Red Hat Cluster Suite
  hosts: all
  become: yes
  tasks:

    - name: Authenticate pcs
      command: pcs cluster auth {{ ansible_play_hosts|join(" ") }} -u hacluster -p {{ foreman_params.hacluster_passwd }}

    - name: Create cluster
      command: pcs cluster setup --start --name {{ ansible_play_hosts|join(" ") }} {{ foreman_params.hacluster_peers }} --force
      run_once: true

    - name: Enable services
      command: pcs cluster enable --all
      run_once: true

    - include: xvm-fencing.yml
      when: foreman_params.hacluster_fencing == 'xvm'

    - include: vmware-fencing.yml
      when: foreman_params.hacluster_fencing == 'vmware'



