---
- name: Configure Red Hat Cluster Suite
  hosts: all
  become: yes
  tasks:

    - name: Authenticate pcs
      command: pcs cluster auth {{ foreman_params.hacluster_peers }} -u hacluster -p {{ foreman_params.hacluster_passwd }}

    - name: Create cluster
      command: pcs cluster setup --start --name {{ foreman_params.hacluster_name }} {{ foreman_params.hacluster_peers }} --force
      run_once: true

    - name: Enable services
      command: pcs cluster enable --all
      run_once: true

    - include: xvm-fencing.yml
      when: foreman_params.hacluster_fencing == 'xvm'

    - include: vmware-fencing.yml
      when: foreman_params.hacluster_fencing == 'vmware'



